<?php

namespace Claroline\VideoPlayerBundle\Controller\API;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class VideoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\VideoPlayerBundle\Controller\API\VideoController($container->get('claroline.manager.video_player_manager', 1), $container->get('request', 1), $container->getParameter('claroline.param.files_directory'), $container->get('security.authorization_checker', 1));
        return $instance;
    }
}
