<?php

namespace Claroline\CoreBundle\Controller\API\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ClientController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\API\Admin\ClientController();
        $instance->_construct($container->get('claroline.manager.oauth_manager', 1));
        return $instance;
    }
}
