<?php

namespace Claroline\CoreBundle\Controller\Widget;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SimpleTextController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Widget\SimpleTextController();
        return $instance;
    }
}
