<?php

namespace Claroline\CoreBundle\Controller\API\Organization;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LocationController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-CoreBundle-Controller-API-Organization-LocationController.php';
        $w = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\API\\Organization\\LocationController' => array('getLocationsAction' => array(0 => 'security.access.method_interceptor'), 'getLocationCreateFormAction' => array(0 => 'security.access.method_interceptor'), 'getLocationEditFormAction' => array(0 => 'security.access.method_interceptor'), 'postLocationAction' => array(0 => 'security.access.method_interceptor'), 'putLocationAction' => array(0 => 'security.access.method_interceptor'), 'deleteLocationAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_d0a094961f1b68639d993e1698636b56505a271a\__CG__\Claroline\CoreBundle\Controller\API\Organization\LocationController($container->get('form.factory', 1), $container->get('claroline.manager.organization.location_manager', 1), $container->get('claroline.manager.api_manager', 1), $container->get('claroline.persistence.object_manager', 1), $container->get('request', 1));
        $instance->__CGInterception__setLoader($w);
        return $instance;
    }
}
