<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdministrationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\AdministrationController($container->get('claroline.event.event_dispatcher', 1), $container->get('claroline.manager.tool_manager', 1), $container->get('security.token_storage', 1), $container);
        return $instance;
    }
}
