<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\UserController($container->get('claroline.manager.facet_manager', 1), $container->get('claroline.manager.group_manager', 1), $container->get('claroline.manager.role_manager', 1), $container->get('translator', 1), $container->get('claroline.manager.user_manager', 1), $container->get('claroline.manager.workspace_manager', 1));
        return $instance;
    }
}
