<?php

namespace Claroline\ImagePlayerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ImagePlayerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\ImagePlayerBundle\Controller\ImagePlayerController();
        return $instance;
    }
}
