<?php

namespace Claroline\TeamBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TeamController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\TeamBundle\Controller\TeamController($container->get('form.factory', 1), $container->get('http_kernel', 1), $container->get('request_stack', 1), $container->get('router', 1), $container->get('security.authorization_checker', 1), $container->get('claroline.manager.team_manager', 1), $container->get('security.token_storage', 1));
        return $instance;
    }
}
