<?php

namespace Claroline\CoreBundle\Controller\API\User;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FacetController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-CoreBundle-Controller-API-User-FacetController.php';
        $z = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\API\\User\\FacetController' => array('getFacetsAction' => array(0 => 'security.access.method_interceptor'), 'createFacetAction' => array(0 => 'security.access.method_interceptor'), 'editFacetAction' => array(0 => 'security.access.method_interceptor'), 'deleteFacetAction' => array(0 => 'security.access.method_interceptor'), 'setFacetRolesAction' => array(0 => 'security.access.method_interceptor'), 'createFacetPanelAction' => array(0 => 'security.access.method_interceptor'), 'createFieldOptionsAction' => array(0 => 'security.access.method_interceptor'), 'deleteFieldOptionsAction' => array(0 => 'security.access.method_interceptor'), 'editFacetPanelAction' => array(0 => 'security.access.method_interceptor'), 'deletePanelFacetAction' => array(0 => 'security.access.method_interceptor'), 'createFieldFacetAction' => array(0 => 'security.access.method_interceptor'), 'editFieldFacetAction' => array(0 => 'security.access.method_interceptor'), 'deleteFieldFacetAction' => array(0 => 'security.access.method_interceptor'), 'putPanelRoleAction' => array(0 => 'security.access.method_interceptor'), 'getProfilePreferencesAction' => array(0 => 'security.access.method_interceptor'), 'putProfilePreferencesAction' => array(0 => 'security.access.method_interceptor'), 'orderPanelsAction' => array(0 => 'security.access.method_interceptor'), 'orderFieldsAction' => array(0 => 'security.access.method_interceptor'), 'invertPropertiesEditableAction' => array(0 => 'security.access.method_interceptor'), 'moveFacetDownAction' => array(0 => 'security.access.method_interceptor'), 'moveFacetUpAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_7b7bf3693ff8502172b2df7e13bea3429886e0dd\__CG__\Claroline\CoreBundle\Controller\API\User\FacetController($container->get('claroline.manager.facet_manager', 1), $container->get('request', 1), $container->get('claroline.persistence.object_manager', 1), $container->get('claroline.manager.profile_property_manager', 1));
        $instance->__CGInterception__setLoader($z);
        return $instance;
    }
}
