<?php

namespace Claroline\CoreBundle\Controller\Administration;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AnalyticsController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-CoreBundle-Controller-Administration-AnalyticsController.php';
        $u = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\Administration\\AnalyticsController' => array('analyticsAction' => array(0 => 'security.access.method_interceptor'), 'analyticsConnectionsAction' => array(0 => 'security.access.method_interceptor'), 'analyticsResourcesAction' => array(0 => 'security.access.method_interceptor'), 'analyticsTopAction' => array(0 => 'security.access.method_interceptor'), 'analyticsItemAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_b81588046393b33e291b27d2503e28eef87a2d0d\__CG__\Claroline\CoreBundle\Controller\Administration\AnalyticsController($container->get('claroline.manager.user_manager', 1), $container->get('claroline.manager.workspace_manager', 1), $container->get('form.factory', 1), $container->get('claroline.manager.analytics_manager', 1), $container->get('request', 1));
        $instance->__CGInterception__setLoader($u);
        return $instance;
    }
}
