<?php

namespace Claroline\ChatBundle\Controller\API;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ChatController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\ChatBundle\Controller\API\ChatController($container->get('security.authorization_checker', 1), $container->get('claroline.manager.chat_manager', 1), $container->get('claroline.config.platform_config_handler', 1), $container->get('security.token_storage', 1), $container->get('request', 1));
        return $instance;
    }
}
