<?php

namespace Claroline\CoreBundle\Controller\Testing;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RemoteTestingController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Testing\RemoteTestingController();
        return $instance;
    }
}
