<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ThemeController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-CoreBundle-Controller-ThemeController.php';
        $e = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\ThemeController' => array('listAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'formAction' => array(0 => 'security.access.method_interceptor'), 'createThemeAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_df471074b3524b4092385e48032f2b938a67b479\__CG__\Claroline\CoreBundle\Controller\ThemeController($container->get('claroline.manager.theme_manager', 1), $container->get('form.factory', 1), $container->get('router', 1));
        $instance->__CGInterception__setLoader($e);
        return $instance;
    }
}
