<?php

namespace Claroline\MessageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MessageController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-MessageBundle-Controller-MessageController.php';
        $fa = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\MessageBundle\\Controller\\MessageController' => array('formForUserAction' => array(0 => 'security.access.method_interceptor'), 'formForGroupAction' => array(0 => 'security.access.method_interceptor'), 'formForWorkspaceAction' => array(0 => 'security.access.method_interceptor'), 'sendAction' => array(0 => 'security.access.method_interceptor'), 'listReceivedAction' => array(0 => 'security.access.method_interceptor'), 'listSentAction' => array(0 => 'security.access.method_interceptor'), 'listRemovedAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'softDeleteAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'restoreFromTrashAction' => array(0 => 'security.access.method_interceptor'), 'markAsReadAction' => array(0 => 'security.access.method_interceptor'), 'contactableUsersListAction' => array(0 => 'security.access.method_interceptor'), 'setMailNotificationAction' => array(0 => 'security.access.method_interceptor'), 'contactableGroupsListAction' => array(0 => 'security.access.method_interceptor'), 'contactableWorkspacesListAction' => array(0 => 'security.access.method_interceptor'), 'checkAccess' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_3977e231ae826a49b1ea0e1da54d8c59cb984496\__CG__\Claroline\MessageBundle\Controller\MessageController($container->get('form.factory', 1), $container->get('claroline.manager.group_manager', 1), $container->get('claroline.manager.mail_manager', 1), $container->get('claroline.manager.message_manager', 1), $container->get('claroline.pager.pager_factory', 1), $container->get('request', 1), $container->get('router', 1), $container->get('security.token_storage', 1), $container->get('claroline.manager.user_manager', 1), $container->get('claroline.security.utilities', 1), $container->get('claroline.manager.workspace_manager', 1));
        $instance->__CGInterception__setLoader($fa);
        return $instance;
    }
}
