<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WorkspaceTagController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\WorkspaceTagController($container->get('claroline.manager.workspace_manager', 1), $container->get('claroline.manager.workspace_tag_manager', 1), $container->get('security.token_storage', 1), $container->get('security.authorization_checker', 1), $container->get('form.factory', 1), $container->get('claroline.security.utilities', 1), $container->get('translator', 1));
        return $instance;
    }
}
