<?php

namespace Claroline\CoreBundle\Controller\Administration;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WorkspacesController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-CoreBundle-Controller-Administration-WorkspacesController.php';
        $o = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\Administration\\WorkspacesController' => array('managementAction' => array(0 => 'security.access.method_interceptor'), 'toggleWorkspaceVisibilityAction' => array(0 => 'security.access.method_interceptor'), 'toggleWorkspacePublicRegistrationAction' => array(0 => 'security.access.method_interceptor'), 'deleteWorkspacesAction' => array(0 => 'security.access.method_interceptor'), 'importWorkspaceFormAction' => array(0 => 'security.access.method_interceptor'), 'importWorkspaceAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_a92098030eac12c989e3cd4d1312669d25c7b4d2\__CG__\Claroline\CoreBundle\Controller\Administration\WorkspacesController($container->get('claroline.manager.workspace_manager', 1), $container->get('claroline.persistence.object_manager', 1), $container->get('claroline.event.event_dispatcher', 1));
        $instance->__CGInterception__setLoader($o);
        return $instance;
    }
}
