<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WorkspaceController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-CoreBundle-Controller-WorkspaceController.php';
        $f = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\WorkspaceController' => array('openAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_b39bbb6938d1c64d6a98ac3e63fdc1c21978fb02\__CG__\Claroline\CoreBundle\Controller\WorkspaceController($container->get('security.authorization_checker', 1), $container->get('event_dispatcher', 1), $container->get('form.factory', 1), $container->get('claroline.manager.home_tab_manager', 1), $container->get('request', 1), $container->get('claroline.manager.resource_manager', 1), $container->get('claroline.manager.role_manager', 1), $container->get('router', 1), $container->get('session', 1), $container->get('claroline.manager.workspace_tag_manager', 1), $container->getParameter('claroline.param.default_template'), $container->get('templating', 1), $container->get('security.token_storage', 1), $container->get('claroline.security.token_updater', 1), $container->get('claroline.manager.tool_manager', 1), $container->get('translator', 1), $container->get('claroline.manager.user_manager', 1), $container->get('claroline.security.utilities', 1), $container->get('claroline.manager.widget_manager', 1), $container->get('claroline.manager.workspace_manager', 1), $container->get('claroline.manager.workspace_model_manager', 1), $container->get('claroline.manager.workspace_user_queue_manager', 1));
        $instance->__CGInterception__setLoader($f);
        return $instance;
    }
}
