<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WorkspaceAnalyticsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\WorkspaceAnalyticsController($container->get('claroline.manager.activity_manager', 1), $container->get('claroline.manager.analytics_manager', 1), $container->get('claroline.manager.resource_manager', 1), $container->get('claroline.manager.role_manager', 1), $container->get('security.token_storage', 1), $container->get('security.authorization_checker', 1), $container->get('templating', 1), $container->get('claroline.manager.user_manager', 1), $container->get('claroline.security.utilities', 1));
        return $instance;
    }
}
