<?php

namespace Claroline\MessageBundle\Controller\API;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MessageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\MessageBundle\Controller\API\MessageController();
        $instance->_construct($container->get('claroline.manager.message_manager', 1));
        return $instance;
    }
}
