<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HomeController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-CoreBundle-Controller-HomeController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\HomeController' => array('typesAction' => array(0 => 'security.access.method_interceptor'), 'publishTypeAction' => array(0 => 'security.access.method_interceptor'), 'renameContentFormAction' => array(0 => 'security.access.method_interceptor'), 'renameContentAction' => array(0 => 'security.access.method_interceptor'), 'changeTemplateFormAction' => array(0 => 'security.access.method_interceptor'), 'changeTemplateAction' => array(0 => 'security.access.method_interceptor'), 'moveContentFormAction' => array(0 => 'security.access.method_interceptor'), 'moveContentAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'reorderAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'createTypeAction' => array(0 => 'security.access.method_interceptor'), 'deletetypeAction' => array(0 => 'security.access.method_interceptor'), 'contentToRegionAction' => array(0 => 'security.access.method_interceptor'), 'collapseAction' => array(0 => 'security.access.method_interceptor'), 'menuSettingsAction' => array(0 => 'security.access.method_interceptor'), 'saveMenuSettingsAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_a232afb78673de2599888a2e581d6374bc48073b\__CG__\Claroline\CoreBundle\Controller\HomeController($container->get('claroline.manager.home_manager', 1), $container->get('request', 1), $container->get('security.authorization_checker', 1), $container->get('templating', 1), $container->get('claroline.common.home_service', 1), $container, $container->get('form.factory', 1));
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
