<?php

namespace Claroline\ForumBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ForumController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\ForumBundle\Controller\ForumController($container->get('security.authorization_checker', 1), $container->get('claroline.manager.forum_manager', 1), $container->get('security.token_storage', 1));
        return $instance;
    }
}
