<?php

namespace Claroline\CoreBundle\Controller\Administration;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class InternationalizationController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/Claroline-CoreBundle-Controller-Administration-InternationalizationController.php';
        $l = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\Administration\\InternationalizationController' => array('formAction' => array(0 => 'security.access.method_interceptor'), 'submitAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_c02517e80c14ccc923722108356cab39f3e4ce83\__CG__\Claroline\CoreBundle\Controller\Administration\InternationalizationController();
        $instance->__CGInterception__setLoader($l);
        return $instance;
    }
}
