<?php

namespace Claroline\CoreBundle\Controller\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ModelController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Tool\ModelController($container->get('form.factory', 1), $container->get('claroline.manager.group_manager', 1), $container->get('claroline.manager.home_tab_manager', 1), $container->get('claroline.manager.workspace_model_manager', 1), $container->get('request', 1), $container->get('claroline.manager.resource_manager', 1), $container->get('claroline.manager.role_manager', 1), $container->get('router', 1), $container->get('security.authorization_checker', 1), $container->get('claroline.manager.user_manager', 1));
        return $instance;
    }
}
