<?php

namespace Claroline\CoreBundle\Controller\API\User;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ApiController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\API\User\ApiController();
        return $instance;
    }
}
