<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LocaleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\LocaleController($container->get('claroline.manager.locale_manager', 1), $container->get('security.token_storage', 1));
        return $instance;
    }
}
