<?php

namespace FormaLibre\SupportBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SupportController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FormaLibre\SupportBundle\Controller\SupportController($container->get('security.authorization_checker', 1), $container->get('event_dispatcher', 1), $container->get('form.factory', 1), $container->get('request_stack', 1), $container->get('router', 1), $container->get('formalibre.manager.support_manager', 1), $container->get('claroline.manager.tool_manager', 1), $container->get('translator', 1));
        return $instance;
    }
}
