<?php

namespace FormaLibre\PresenceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminPresenceController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/FormaLibre-PresenceBundle-Controller-AdminPresenceController.php';
        $la = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FormaLibre\\PresenceBundle\\Controller\\AdminPresenceController' => array('adminToolIndexAction' => array(0 => 'security.access.method_interceptor'), 'adminAddSchoolYearAction' => array(0 => 'security.access.method_interceptor'), 'SchoolYearModifAction' => array(0 => 'security.access.method_interceptor'), 'SchoolYearSupprimerAction' => array(0 => 'security.access.method_interceptor'), 'adminRightAction' => array(0 => 'security.access.method_interceptor'), 'adminHoraireAction' => array(0 => 'security.access.method_interceptor'), 'adminModifierHoraireAction' => array(0 => 'security.access.method_interceptor'), 'adminPeriodSupprimerAction' => array(0 => 'security.access.method_interceptor'), 'adminListingRolesAction' => array(0 => 'security.access.method_interceptor'), 'StatusModifAction' => array(0 => 'security.access.method_interceptor'), 'StatussupprimerAction' => array(0 => 'security.access.method_interceptor'), 'ListingStatusByDefaultAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_2e4a250a4d7b750338bf3e8341113b621eb52124\__CG__\FormaLibre\PresenceBundle\Controller\AdminPresenceController($container->get('claroline.persistence.object_manager', 1), $container->get('doctrine.orm.entity_manager', 1), $container->get('router', 1), $container->get('claroline.config.platform_config_handler', 1), $container->get('formalibre.manager.presence_manager', 1));
        $instance->__CGInterception__setLoader($la);
        return $instance;
    }
}
