<?php

namespace HeVinci\FavouriteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FavouriteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \HeVinci\FavouriteBundle\Controller\FavouriteController($container->get('claroline.manager.resource_manager', 1));
        return $instance;
    }
}
