<?php

namespace HeVinci\UrlBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UrlController__JMSInjector
{
    public static function inject($container) {
        $instance = new \HeVinci\UrlBundle\Controller\UrlController($container->get('form.factory', 1), $container->get('claroline.persistence.object_manager', 1), $container->get('request_stack', 1), $container->get('hevinci_url.manager.url', 1));
        return $instance;
    }
}
