<?php

namespace HeVinci\CompetencyBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PickerController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/HeVinci-CompetencyBundle-Controller-PickerController.php';
        $oa = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('HeVinci\\CompetencyBundle\\Controller\\PickerController' => array('frameworksAction' => array(0 => 'security.access.method_interceptor'), 'competenciesAction' => array(0 => 'security.access.method_interceptor'), 'levelsAction' => array(0 => 'security.access.method_interceptor'), 'suggestUserAction' => array(0 => 'security.access.method_interceptor'), 'suggestGroupAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_03171c5b949412ae5494a9173118e81350c82044\__CG__\HeVinci\CompetencyBundle\Controller\PickerController($container->get('hevinci.competency.competency_manager', 1));
        $instance->__CGInterception__setLoader($oa);
        return $instance;
    }
}
