<?php

namespace HeVinci\CompetencyBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ObjectiveController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/HeVinci-CompetencyBundle-Controller-ObjectiveController.php';
        $pa = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('HeVinci\\CompetencyBundle\\Controller\\ObjectiveController' => array('objectivesAction' => array(0 => 'security.access.method_interceptor'), 'newObjectiveAction' => array(0 => 'security.access.method_interceptor'), 'createObjectiveAction' => array(0 => 'security.access.method_interceptor'), 'deleteObjectiveAction' => array(0 => 'security.access.method_interceptor'), 'objectiveEditionFormAction' => array(0 => 'security.access.method_interceptor'), 'editObjectiveAction' => array(0 => 'security.access.method_interceptor'), 'linkCompetencyAction' => array(0 => 'security.access.method_interceptor'), 'deleteCompetencyLinkAction' => array(0 => 'security.access.method_interceptor'), 'objectiveCompetenciesAction' => array(0 => 'security.access.method_interceptor'), 'userObjectiveCompetenciesAction' => array(0 => 'security.access.method_interceptor'), 'usersAction' => array(0 => 'security.access.method_interceptor'), 'objectiveUsersAction' => array(0 => 'security.access.method_interceptor'), 'groupUsersAction' => array(0 => 'security.access.method_interceptor'), 'groupsAction' => array(0 => 'security.access.method_interceptor'), 'objectiveGroupsAction' => array(0 => 'security.access.method_interceptor'), 'assignObjectiveToUserAction' => array(0 => 'security.access.method_interceptor'), 'assignObjectiveToGroupAction' => array(0 => 'security.access.method_interceptor'), 'loadUserObjectivesAction' => array(0 => 'security.access.method_interceptor'), 'removeUserObjectiveAction' => array(0 => 'security.access.method_interceptor'), 'removeGroupObjectiveAction' => array(0 => 'security.access.method_interceptor'), 'loadGroupObjectivesAction' => array(0 => 'security.access.method_interceptor'), 'competencyUserHistoryAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_9382b7860f227ad5b11f42c8aca08f1d46d3445d\__CG__\HeVinci\CompetencyBundle\Controller\ObjectiveController($container->get('hevinci.form.handler', 1), $container->get('hevinci.competency.objective_manager', 1), $container->get('hevinci.competency.progress_manager', 1));
        $instance->__CGInterception__setLoader($pa);
        return $instance;
    }
}
