<?php

namespace HeVinci\CompetencyBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MyObjectiveController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/HeVinci-CompetencyBundle-Controller-MyObjectiveController.php';
        $na = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('HeVinci\\CompetencyBundle\\Controller\\MyObjectiveController' => array('objectivesAction' => array(0 => 'security.access.method_interceptor'), 'userObjectiveCompetenciesAction' => array(0 => 'security.access.method_interceptor'), 'competencyUserHistoryAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_f9b6a9db864b98c201090157113671890879a58a\__CG__\HeVinci\CompetencyBundle\Controller\MyObjectiveController($container->get('hevinci.competency.objective_manager', 1), $container->get('hevinci.competency.progress_manager', 1));
        $instance->__CGInterception__setLoader($na);
        return $instance;
    }
}
