<?php

namespace HeVinci\CompetencyBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WidgetController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/claroline/app/cache/prod/jms_diextra/proxies/HeVinci-CompetencyBundle-Controller-WidgetController.php';
        $qa = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('HeVinci\\CompetencyBundle\\Controller\\WidgetController' => array('objectivesAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy878b27ff_807cd56e3f24f6f55e8b794d8f05e17562b67800\__CG__\HeVinci\CompetencyBundle\Controller\WidgetController($container->get('hevinci.competency.objective_manager', 1));
        $instance->__CGInterception__setLoader($qa);
        return $instance;
    }
}
