<?php

namespace Icap\WebsiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WebsiteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\WebsiteBundle\Controller\WebsiteController();
        return $instance;
    }
}
