<?php

namespace Icap\NotificationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class NotificationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\NotificationBundle\Controller\NotificationController();
        return $instance;
    }
}
