<?php

namespace Icap\BlogBundle\Controller\API;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ApiController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\BlogBundle\Controller\API\ApiController();
        return $instance;
    }
}
