<?php

namespace Icap\PortfolioBundle\Controller\Internal;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PortfolioController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\PortfolioBundle\Controller\Internal\PortfolioController();
        return $instance;
    }
}
