<?php

namespace Icap\SocialmediaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LikeActionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\SocialmediaBundle\Controller\LikeActionController();
        return $instance;
    }
}
