<?php

namespace Icap\BadgeBundle\Controller\Internal;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserBadgeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\BadgeBundle\Controller\Internal\UserBadgeController();
        return $instance;
    }
}
