<?php

namespace Icap\BadgeBundle\Controller\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BadgeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\BadgeBundle\Controller\Tool\BadgeController();
        return $instance;
    }
}
