<?php

namespace Icap\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WidgetController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\BlogBundle\Controller\WidgetController();
        return $instance;
    }
}
