<?php

namespace Icap\OAuthBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ConnexionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\OAuthBundle\Controller\ConnexionController();
        return $instance;
    }
}
