<?php

namespace Icap\BadgeBundle\Controller\Internal;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CollectionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\BadgeBundle\Controller\Internal\CollectionController();
        return $instance;
    }
}
