<?php

namespace Innova\PathBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PathController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Innova\PathBundle\Controller\PathController();
        return $instance;
    }
}
