<?php

namespace JMS\TwigJsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DemoCompilationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \JMS\TwigJsBundle\Controller\DemoCompilationController();
        return $instance;
    }
}
