<?php

namespace UJM\ExoBundle\Controller\Api;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AbstractController__JMSInjector
{
    public static function inject($container) {
        $instance = new \UJM\ExoBundle\Controller\Api\AbstractController();
        return $instance;
    }
}
