<?php

namespace UJM\ExoBundle\Controller\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class QuestionBankController__JMSInjector
{
    public static function inject($container) {
        $instance = new \UJM\ExoBundle\Controller\Tool\QuestionBankController($container->get('ujm_exo.manager.question', 1), $container->get('ujm_exo.serializer.user', 1));
        return $instance;
    }
}
