(function(){$(function(){var locationhash=window.location.hash;if(locationhash.substr(0,2)=="#!"){$("#portfolio_space_tabs a[href='#"+locationhash.substr(2)+"']").tab("show");}
toastr.options={"closeButton":true,"positionClass":"toast-top-center","showDuration":"300","hideDuration":"1000","timeOut":"3000","extendedTimeOut":"1000","showEasing":"swing","hideEasing":"linear","showMethod":"fadeIn","hideMethod":"fadeOut"};var modal=window.Claroline.Modal;var elementsToModalized=[{target:"a.modal_action",message:Translator.trans('portfolio_added_ajax_notification',{},'icap_portfolio'),exchangeSpaceNeedUpdate:true},{target:"#no_portfolio a",message:Translator.trans('portfolio_added_ajax_notification',{},'icap_portfolio'),exchangeSpaceNeedUpdate:true},{target:"a.rename_link",message:Translator.trans('portfolio_renamed_ajax_notification',{},'icap_portfolio'),exchangeSpaceNeedUpdate:true},{target:"a.update_visibility_link",message:Translator.trans('portfolio_update_visibility_ajax_notification',{},'icap_portfolio'),exchangeSpaceNeedUpdate:false},{target:"a.update_guides_link",message:Translator.trans('portfolio_update_guides_ajax_notification',{},'icap_portfolio'),exchangeSpaceNeedUpdate:false}];elementsToModalized.forEach(function(element,index){modalized(element);});$('#list').on('click','.exchange_link',function(event){var scope=angular.element($("#exchange_space_container")).scope();scope.$apply(function(){var portfolioId=$(event.currentTarget).val();if(portfolioId!==scope.selectedPortfolioId){scope.clickOnPortolio(portfolioId);}
$('#portfolio_space_tabs a[href="#exchange_space"]').tab('show');});});$('#list').on('click','.delete',function(event){event.preventDefault();var deleteLink=$(event.target);deleteLink.confirmModal({confirmCallback:deleteConfirmCallback,confirmDismiss:false,confirmAutoOpen:true});});$('#list').on('click','.pagination a',function(event){event.preventDefault();$.ajax({url:event.target.href,success:function(data,textStatus,jqXHR){updateList(data);}});});$('#import_action a').click(function(event){event.preventDefault();modal.displayForm(event.target.href,function(data){$.ajax({url:window.location,success:function(data,textStatus,jqXHR){updateList(data);updateExchangeSpace();toastr.success(Translator.trans('portfolio_imported_ajax_notification',{},'icap_portfolio'));}});},function(data){},'portfolio_import')});function deleteConfirmCallback(target,modal){$.ajax({url:$(target).attr('href'),success:function(data,textStatus,jqXHR){updateList(data);updateExchangeSpace();toastr.success(Translator.trans('portfolio_deleted_ajax_notification',{},'icap_portfolio'));modal.modal('hide');}});}
function submitForm(modalElement,form,message,exchangeSpaceNeedUpdate){$.ajax({url:form.attr('action'),data:form.serializeArray(),type:'POST',success:function(data,textStatus,jqXHR){updateList(data);if(exchangeSpaceNeedUpdate){updateExchangeSpace();}
modalElement.modal('hide');toastr.success(message);}});}
function modalized(element){$('#list').on('click',element.target,function(event){event.preventDefault();modal.fromUrl(event.target.href,function(modalElement){var modalForm=$("form",modalElement);modalElement.on('click','button[type="submit"]',function(event){event.preventDefault();submitForm(modalElement,modalForm,element.message,element.exchangeSpaceNeedUpdate);});modalElement.on('keypress',function(event){if(event.keyCode===13&&event.target.nodeName!=='TEXTAREA'){event.preventDefault();submitForm(modalElement,modalForm,element.message,element.exchangeSpaceNeedUpdate);}});});});}
function updateList(content){$("#list").html(content);}
function updateExchangeSpace(){var scope=angular.element($("#exchange_space_container")).scope();scope.$apply(function(){scope.refreshComments(false);});}});})();
angular.module('angular-toArrayFilter',[]).filter('toArray',function(){return function(obj,addKey){if(!angular.isObject(obj))return obj;if(addKey===false){return Object.keys(obj).map(function(key){return obj[key];});}else{return Object.keys(obj).map(function(key){var value=obj[key];return angular.isObject(value)?Object.defineProperty(value,'$key',{enumerable:false,value:key}):{$key:key,$value:value};});}};});
Array.prototype.remove=function(value){var index=this.indexOf(value);if(index!=-1){return this.splice(index,1);}
return false;}
Array.prototype.inArray=function(value){var index=this.indexOf(value);if(index!=-1){return true;}
return false;}
Array.prototype.diff=function(part){return this.filter(function(element){return part.indexOf(element)<0;});};
'use strict';var commentsApp=angular.module('commentsApp',['ngResource','ngSanitize','ngAnimate','ui.tinymce','app.translation','app.interpolator','app.directives','angular-toArrayFilter','app.config']);commentsApp.config(["$httpProvider",function($http){var elementToRemove=['title','id','type','unreadComments'];$http.defaults.transformRequest.push(function(data){data=angular.fromJson(data);angular.forEach(data,function(element,index){if(elementToRemove.inArray(index)){delete data[index];}});return JSON.stringify(data);});}]);commentsApp.value('assetPath',window.assetPath);
'use strict';commentsApp.controller("portfoliosController",["$scope","portfolioManager","commentsManager","$filter",function($scope,portfolioManager,commentsManager,$filter){$scope.selectedPortfolioId=0;$scope.selectedPortfolio=null;$scope.clickOnPortolio=function(portfolioId){if(portfolioId!==$scope.selectedPortfolioId){$scope.selectedPortfolioId=portfolioId;$scope.selectedPortfolio=$filter('filter')($scope.portfolios,{id:$scope.selectedPortfolioId})[0];$scope.updateCountViewComments();}else{$scope.selectedPortfolioId=0;$scope.selectedPortfolio=null;}
commentsManager.loadComments($scope.selectedPortfolioId);};$scope.refreshComments=function(clickOnPortfolio){$scope.portfolios=portfolioManager.getPortfolios();$scope.portfolios.then(function(data){$scope.portfolios=data;if(clickOnPortfolio){$scope.clickOnPortolio(window.currentPortfolioId);}},function(errorPayload){console.error('failure loading portfolios',errorPayload);});};$scope.updateCountViewComments=function(){if(0<$scope.selectedPortfolio.unreadComments){portfolioManager.updateViewCommentsDate($scope.selectedPortfolio);}};$scope.refreshComments(true);}]);
'use strict';commentsApp.controller("commentsController",["$scope","$timeout","commentsManager","assetPath","tinyMceConfig",function($scope,$timeout,commentsManager,assetPath,tinyMceConfig){$scope.comments=commentsManager.comments;$scope.tinyMceConfig=tinyMceConfig;$scope.assetPath=assetPath;$scope.addComment=function(portfolioId,message){commentsManager.addComment(portfolioId,message);};}]);
'use strict';commentsApp.directive("portfolioContainer",function(){return{restrict:"AC",controller:"portfoliosController"};});
'use strict';commentsApp.directive("commentContainer",function(){return{restrict:"AC",controller:"commentsController"};});
'use strict';commentsApp.factory('portfolioManager',["$http","$q","portfolioFactory",function($http,$q,portfolioFactory){return{portfolios:[],getPortfolios:function(){var deferred=$q.defer();$http.get(Routing.generate("icap_portfolio_internal_portfolio")).success(function(data){var portfolios=[];angular.forEach(data,function(rawPortfolio){portfolios.push(new portfolioFactory(rawPortfolio));});portfolios.$resolved=true;deferred.resolve(portfolios);}).error(function(msg,code){deferred.reject(msg);});return deferred.promise;},save:function(portfolio){var success=function(){};var failed=function(error){console.error('Error occured while saving widget');console.log(error);}
return portfolio.$update(success,failed);},updateViewCommentsDate:function(portfolio){portfolio.commentsViewAt=new Date();this.save(portfolio);}};}]);
'use strict';commentsApp.factory("commentsManager",["$http","commentFactory","urlInterpolator",function($http,commentFactory,urlInterpolator){return{comments:[],create:function(portfolioId,rawComment){var emptyComment=commentFactory.getComment(portfolioId);var comment=new emptyComment(rawComment);this.comments.push(comment);this.save(comment);},save:function(comment){var success=function(){};var failed=function(error){console.log(error);}
return comment.$save(success,failed);},loadComments:function(portfolioId){this.comments.length=0;if(portfolioId){this.comments.$resolved=false;var url=urlInterpolator.interpolate('/{{portfolioId}}/comment',{portfolioId:portfolioId});var self=this;$http.get(url).success(function(data){angular.forEach(data,function(rawComment){var comment=commentFactory.getComment(portfolioId);this.comments.push(new comment(rawComment));},self);self.comments.$resolved=true;});}
else{this.comments.$resolved=true;}},addComment:function(portfolioId,message){if(0<portfolioId){this.create(portfolioId,{message:message})}}};}]);
'use strict';commentsApp.factory("commentFactory",["$resource",function($resource){return{baseUrl:Routing.generate("icap_portfolio_internal_portfolio"),portfolioId:null,getComment:function(portfolioId){this.portfolioId=portfolioId;var comment=$resource(this.baseUrl+"/:portfolioId/comment/:id",{portfolioId:portfolioId,id:"@id"},{get:{method:"GET"},create:{method:"GET"},save:{method:"POST"},remove:{method:"DELETE"}});comment.prototype.message='';return comment;}}}]);
'use strict';commentsApp.factory("portfolioFactory",["$resource",function($resource){var url=Routing.generate("icap_portfolio_internal_portfolio")+"/comments/:portfolioId";var portfolio=$resource(url,{portfolioId:"@id"},{update:{method:"PUT"}});return portfolio;}]);
'use strict';var widgetsApp=angular.module('widgetsApp',['ngResource','ngSanitize','ngAnimate','ui.tinymce','ui.resourcePicker','ui.badgePicker','ui.datepicker','datetime','mgcrea.ngStrap.popover','ui.bootstrap.collapse','app.translation','app.interpolator','app.directives','app.config']);widgetsApp.config(["$httpProvider",function($http){var elementToRemove=['views','isCollapsed','isEditing','isUpdating','isDeleting','isNew'];$http.defaults.transformRequest.push(function(data){data=angular.fromJson(data);angular.forEach(data,function(element,index){if(elementToRemove.inArray(index)){delete data[index];}});return JSON.stringify(data);});}]);widgetsApp.value('assetPath',window.assetPath);
'use strict';widgetsApp.controller("widgetController",["$scope","widgetManager","$attrs","tinyMceConfig",function($scope,widgetManager,$attrs,tinyMceConfig){$scope.widgetType=$attrs['widgetContainer'];$scope.tinyMceConfig=tinyMceConfig;$scope.create=function(){widgetManager.create($scope.widgetType);};$scope.edit=function(widget){widgetManager.edit(widget);};$scope.delete=function(widget){widgetManager.delete(widget);};$scope.cancelEdition=function(widget){widgetManager.cancelEditing(widget,true);};$scope.save=function(widget){return widgetManager.save(widget);};}]);
'use strict';widgetsApp.directive("widgetContainer",function(){return{restrict:"AC",controller:"widgetController",scope:true};});
'use strict';widgetsApp.factory("widgetManager",["$http","$q","widgetFactory","$filter",function($http,$q,widgetFactory,$filter){return{widgets:[],emptyWidget:[],form:[],init:function(){var deferred=$q.defer();var self=this;$http.get(Routing.generate("icap_portfolio_internal_widget")).success(function(data){angular.forEach(data,function(rawWidget){var widget=widgetFactory.getWidget(rawWidget.type);var newWidget=new widget(rawWidget);newWidget.isNew=false;self.widgets.push(newWidget);});deferred.resolve(self.widgets);}).error(function(msg,code){deferred.reject(msg);});return deferred.promise;},create:function(type){var newWidget;var widget=widgetFactory.getWidget(type);if(this.emptyWidget[type]){newWidget=new widget(angular.copy(this.emptyWidget[type]));newWidget.id=new Date().getTime();this.edit(newWidget);}
else{newWidget=widget.create();var self=this;newWidget.$promise.then(function(){self.emptyWidget[type]=angular.copy(newWidget);self.edit(newWidget);});}
newWidget.isEditing=true;this.widgets.push(newWidget);},edit:function(widget){widget.copy=angular.copy(widget);if(!widget.isEditing){widget.isEditing=true;widget.isCollapsed=false;this.loadForm(widget);}},loadForm:function(widget){if(this.form[widget.type]){widget.setFormView(this.form[widget.type]);return true;}
var self=this;return $http.get(widget.getFormUrl()).success(function(formViewData){widget.setFormView(formViewData.form);self.form[widget.type]=formViewData.form;});},cancelEditing:function(widget,rollback){if(rollback){angular.copy(widget.copy,widget);}
widget.isEditing=false;if(widget.isNew){this.widgets.remove(widget);}},delete:function(widget){widget.isDeleting=true;var self=this;var success=function(){self.widgets.remove(widget);};var failed=function(error){console.error('Error occured while deleting widget');console.log(error);}
widget.$delete(success,failed).then(function(){widget.isDeleting=false;});},save:function(widget){widget.isUpdating=true;delete widget.copy;widget.deleteChildren();var self=this;var success=function(){widget.isNew=false;self.cancelEditing(widget);widget.isUpdating=false;};var failed=function(error){console.error('Error occured while saving widget');console.log(error);}
if(widget.isNew){delete widget.id;}
return widget.isNew?widget.$save(success,failed):widget.$update(success,failed);}};}]);
'use strict';widgetsApp.factory("widgetFactory",["$resource","urlInterpolator",function($resource,urlInterpolator){return{baseUrl:Routing.generate("icap_portfolio_internal_widget"),widgetResources:[],getWidget:function(type){if(this.widgetResources[type]){return this.widgetResources[type];}
var baseUrl=this.baseUrl+"/:type/:id";var widget=$resource(baseUrl,{type:type,id:"@id"},{get:{method:"GET"},create:{method:"GET"},save:{method:"POST"},update:{method:"PUT"},remove:{method:"DELETE"}});widget.prototype.isNew=true;widget.prototype.type=type;widget.prototype.isEditing=false;widget.prototype.isUpdating=false;widget.prototype.isDeleting=false;widget.prototype.isCollapsed=false;widget.prototype.generateUrl=function(action){var parameters={};parameters.type=type;parameters.action=action;return urlInterpolator.interpolate("/widget/{{type}}/{{action}}",parameters);};widget.prototype.getRenderUrl=function(){return this.generateUrl("render");};widget.prototype.getFormUrl=function(){return this.generateUrl("form");};widget.prototype.setFormView=function(formView){this.views.form=formView;};widget.prototype.getType=function(){return this.type;};widget.prototype.deleteChildren=function(){if(this.children){var childrenToDelete=[];for(var i=0;i<this.children.length;i++){var currentChild=this.children[i];if(currentChild.toDelete||(undefined!==currentChild.added&&!currentChild.added)){childrenToDelete.push(currentChild);}}
for(var i=0;i<childrenToDelete.length;i++){this.children.remove(childrenToDelete[i]);}}};this.widgetResources[type]=widget;return this.widgetResources[type];}}}]);
(function(){'use strict';var appDirectives=angular.module('app.config',[]);var tinymce=window.tinymce;tinymce.claroline.init=tinymce.claroline.init||{};tinymce.claroline.plugins=tinymce.claroline.plugins||{};var plugins=['autoresize advlist autolink lists link image charmap print preview hr anchor pagebreak','searchreplace wordcount visualblocks visualchars fullscreen','insertdatetime media nonbreaking save table directionality','template paste textcolor emoticons code -mention -accordion -codemirror'];var toolbar1='bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | fullscreen displayAllButtons';$.each(tinymce.claroline.plugins,function(key,value){if('autosave'!=key&&value===true){plugins.push(key);toolbar1+=' '+key;}});var tinyMceConfig={};for(var prop in tinymce.claroline.configuration){if(tinymce.claroline.configuration.hasOwnProperty(prop)){tinyMceConfig[prop]=tinymce.claroline.configuration[prop];}}
tinyMceConfig.plugins=plugins;tinyMceConfig.toolbar1=toolbar1;appDirectives.value('tinyMceConfig',tinyMceConfig);})();
'use strict';var appTranslation=angular.module('app.translation',[]);appTranslation.factory('translationService',function(){return{trans:function(key,translationDomain){return Translator.trans(key,{},translationDomain||'icap_portfolio');}};}).filter('trans',["translationService",function(translationService){return function(key){return translationService.trans(key);};}]);
'use strict';var appInterpolator=angular.module('app.interpolator',[]);appInterpolator.service("urlInterpolator",["$interpolate",function($interpolate){return{interpolate:function(text,parameters){var interpolatedUrl=$interpolate(Routing.generate("icap_portfolio_internal_portfolio")+text);return interpolatedUrl(parameters);}};}]);
'use strict';var appDirectives=angular.module('app.directives',[]);appDirectives.directive('scrollContainer',["commentsManager","$timeout",function(commentsManager,$timeout){return{restrict:"A",link:function($scope,element,attrs){$scope.comments=commentsManager.comments;$scope.$watch('comments.length',function(newValue,oldValue){if(newValue>=oldValue){$timeout(function(){element[0].scrollTop=element[0].scrollHeight;},0);}});}};}]);
angular.module('ui.datepicker',[]).directive('bDatepicker',function(){return{require:'?ngModel',restrict:'A',link:function($scope,element,attrs,ngModel){return attrs.$observe('bDatepicker',function(format){var options={format:format,autoclose:true};var onShow=null;if(attrs.singleDate){onShow=function(){if(element.datepicker('getDate')==null){element.datepicker('setDate',element.find('input').val());}}}
return element.datepicker(options).on('show',onShow);});}};});
'use strict';angular.module('ui.badgePicker',[]).directive('uiBadgePicker',function(){var url=Routing.generate("icap_badge_badge_picker");var data={mode:"user"};var successCallback=function(nodes){return null;};return{restrict:"A",link:function($scope,element,attrs){var customData={};var successCallback=successCallback;if(attrs.uiBadgePicker){var badgepickerConfig=$scope.$eval(attrs.uiBadgePicker);customData=badgepickerConfig.data||{};successCallback=badgepickerConfig.successCallback||successCallback;}
angular.extend(data,customData);var closeCallback=function(nodes){var newSelectedValue=[];angular.forEach(nodes,function(element,index){newSelectedValue.push(element.id);});this.data.value=newSelectedValue;};window.Claroline.BadgePicker.configureBadgePicker(url,data,successCallback,closeCallback);$scope.badgePickerOpen=function(){window.Claroline.BadgePicker.openBadgePicker();};element[0].onclick=function(event){event.preventDefault();$scope.badgePickerOpen();};}};});
'use strict';appDirectives.directive("bindHtml",["$compile",function($compile){return function(scope,element,attrs){scope.$watch(attrs.bindHtml,function(html){if(html){element.html(html);$compile(element.contents())(scope);}});};}])
'use strict';appDirectives.directive('loadingForm',["$parse",function($parse){function link(scope,element,attributes){var longOperation=$parse(attributes['loadingForm']);var button=element.find("button[type=submit]");var buttonHtml=button.html();element.on('submit',function(event){scope.$apply(function(){button.attr("disabled",true);button.prepend('<span class="loading"></span> ');longOperation(scope,{$event:event}).then(function(data){button.attr("disabled",false);button.html(buttonHtml);},function(res){button.attr("disabled",false);button.html(buttonHtml);});});});}
var directive={link:link,restrict:'A'};return directive;}]);
'use strict';appDirectives.directive('confirmClick',["$parse","translationService",function($parse,translationService){var link=function(scope,element,attributes){var clickAction=attributes.confirmClick;element.confirmModal({'confirmTitle':translationService.trans('widget_delete_confirm_title'),'confirmMessage':translationService.trans('widget_delete_confirm_message'),'confirmOk':translationService.trans('widget_delete_confirm_ok'),'confirmCancel':translationService.trans('widget_delete_confirm_cancel'),'confirmCallback':function(){scope.$eval(clickAction)}});}
var directive={link:link,restrict:'A'};return directive;}]);
'use strict';appDirectives.controller("collectionFormController",["$scope","$attrs",function($scope,$attrs){$scope.emptyChild=jQuery.parseJSON($attrs.collectionForm.replace(/'/g,'"'));$scope.emptyChild.added=false;$scope.collection=$scope.widget.children||[];$scope.resourcePickerConfig={isPickerMultiSelectAllowed:true,callback:function(nodes){angular.forEach(nodes,function(element,index){var newChild=angular.copy($scope.emptyChild);newChild.resource=index;newChild.id=index;newChild.name=element[0];delete newChild.added;$scope.collection.push(newChild);});$scope.$apply();}};var selectedValue=[];angular.forEach($scope.collection,function(element,index){selectedValue.push(element.badge);});$scope.badgePickerConfig={data:{multiple:true,value:selectedValue},successCallback:function(nodes){var receivedValue=[];angular.forEach(nodes,function(element,index){receivedValue.push(element.id);});var badgeToRemove=selectedValue.diff(receivedValue);var badgeToAdd=receivedValue.diff(selectedValue);angular.forEach($scope.collection,function(element,index){var id=parseInt(element.badge);if(badgeToRemove.inArray(id)){$scope.deleteChild(element);}});angular.forEach(nodes,function(element,index){var id=parseInt(element.id);if(badgeToAdd.inArray(id)){var badgeAboutToBeDelete=$scope.collection.filter(function(element){return id===element.badge;});if(0<badgeAboutToBeDelete.length){delete badgeAboutToBeDelete[0].toDelete;}
else{var newChild=angular.copy($scope.emptyChild);newChild.badge=id;newChild.name=element.text;newChild.img=element.icon;delete newChild.added;$scope.addChild(newChild);}}});$scope.$apply();selectedValue=[];angular.forEach($scope.collection,function(element,index){if(!element.toDelete){selectedValue.push(element.badge);}});}};$scope.addChild=function(child){$scope.collection.push(child);};$scope.deleteChild=function(child){child.toDelete=true;};$scope.cancelDeletionOfChild=function(child){delete child.toDelete;};$scope.isEmpty=function(child){var isEmpty=false;for(var attribute in child){if("$"!==attribute[0]&&''===child[attribute]){isEmpty=true;}}
return isEmpty;}
$scope.modify=function(child,index){if($scope.isEmpty(child)){child.added=false;}
else{if(false==child.added&&(index+1)===$scope.collection.length){$scope.collection.push(angular.copy($scope.emptyChild));delete child.added;}}};$scope.isAdded=function(child){return(!$scope.isEmpty(child)&&!child.toDelete)||child.toDelete;};if(!$scope.isEmpty($scope.collection[$scope.collection.length-1])&&!$attrs.editable){$scope.collection.push(angular.copy($scope.emptyChild));}}]);
'use strict';appDirectives.directive("collectionForm",function(){return{scope:true,restrict:'A',controller:"collectionFormController"};});
'use strict';var statisticsApp=angular.module('statisticsApp',['angular-toArrayFilter','daterangepicker']);
'use strict';statisticsApp.controller("statisticsViewController",["$scope","portfolioManager","$filter","$http","urlInterpolator","translationService",function($scope,portfolioManager,$filter,$http,urlInterpolator,translationService){$scope.selectedPortfolio='';$scope.period={date:{startDate:moment().startOf('month'),endDate:moment().endOf('month')}};$scope.daterangepickerOptions={ranges:window.ranges,separator:" "+translationService.trans('date_range.separator','platform')+" ",clearClass:"btn hide",eventHandlers:{"apply.daterangepicker":fetchVisitData},locale:{format:translationService.trans('date_range.js_format','platform'),applyLabel:translationService.trans('date_range.apply','platform'),clearLabel:translationService.trans('date_range.clear','platform'),fromLabel:translationService.trans('date_range.from','platform'),toLabel:translationService.trans('date_range.to','platform'),weekLabel:translationService.trans('date_range.week','platform'),customRangeLabel:translationService.trans('date_range.custom_range','platform'),daysOfWeek:JSON.parse(translationService.trans('date_range.day_names','platform')),monthNames:JSON.parse(translationService.trans('date_range.month_names','platform')),firstDay:parseInt(translationService.trans('date_range.first_day','platform'))}};$scope.chartData=[];$scope.fetchingChartData=false;var bg_color="transparent";if(navigator.userAgent.match(/msie/i)&&navigator.userAgent.match(/8/))bg_color="#fff";$scope.chartOptions={title:{show:false},grid:{drawBorder:true,borderWidth:1.0,shadow:false,background:bg_color},axesDefaults:{labelRenderer:$.jqplot.CanvasAxisLabelRenderer,tickRenderer:$.jqplot.CanvasAxisTickRenderer},axes:{xaxis:{renderer:$.jqplot.DateAxisRenderer,tickOptions:{formatString:translationService.trans('jqplot_date_output_format','platform'),showGridline:false,showMark:true,angle:-20,fontSize:'10px'},numberTicks:10},yaxis:{min:0,showTickMarks:true,numberTicks:5}},highlighter:{show:true,sizeAdjust:1,tooltipOffset:12,tooltipLocation:'n',tooltipAxes:'xy',formatString:'%s <br/> %d',tooltipFadeSpeed:'fast'},cursor:{show:true,zoom:true,showTooltip:false},seriesDefaults:{showMarker:(true),markerOptions:{shadow:false},shadow:false,showLine:true,useNegativeColors:false,fill:true,lineWidth:1.5,fillAndStroke:true,fillAlpha:0.12,rendererOptions:{highlightMouseOver:true,highlightMouseDown:true}}};$scope.fetchVisitData=fetchVisitData;function fetchVisitData(){if($scope.selectedPortfolio!=''){$scope.fetchingChartData=true;$('#chart').replaceWith('<div id="chart"></div>');var url=urlInterpolator.interpolate('/analytics/{{portfolioId}}/views/{{startDate}}/{{endDate}}',{portfolioId:$scope.selectedPortfolio,startDate:$scope.period.date.startDate.format('DD-MM-YYYY'),endDate:$scope.period.date.endDate.format('DD-MM-YYYY')});var self=this;$http.get(url).success(function(data){$scope.fetchingChartData=false;$scope.chartData=data;if($scope.chartData.length>0){$.jqplot('chart',[data],$scope.chartOptions);}});}};}]);
'use strict';statisticsApp.directive("statisticsViewContainer",function(){return{restrict:"AC",scope:true,controller:"statisticsViewController"};});
'use strict';var indexApp=angular.module("indexApp",["commentsApp","widgetsApp","statisticsApp"]);
'use strict';indexApp.directive("indexContainer",function(){return{restrict:"AC",controller:"indexController",scope:true};});
'use strict';indexApp.controller("indexController",["$scope","widgetManager","assetPath",function($scope,widgetManager,assetPath){$scope.assetPath=assetPath;$scope.widgets=widgetManager.init();$scope.widgets.then(function(widgets){$scope.widgets=widgets;$scope.widgets.$resolved=true;});}]);