<?php

namespace Proxies\__CG__\Innova\CollecticielBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notation extends \Innova\CollecticielBundle\Entity\Notation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'user', 'document', 'dropzone', 'choiceCriterias', 'note', 'appreciation', 'commentText', 'qualityText', 'noteDate', 'recordOrTransmit'];
        }

        return ['__isInitialized__', 'id', 'user', 'document', 'dropzone', 'choiceCriterias', 'note', 'appreciation', 'commentText', 'qualityText', 'noteDate', 'recordOrTransmit'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Notation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentText($commentText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentText', [$commentText]);

        return parent::setCommentText($commentText);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentText', []);

        return parent::getCommentText();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualityText($qualityText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualityText', [$qualityText]);

        return parent::setQualityText($qualityText);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualityText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualityText', []);

        return parent::getQualityText();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoteDate($noteDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoteDate', [$noteDate]);

        return parent::setNoteDate($noteDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoteDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoteDate', []);

        return parent::getNoteDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Claroline\CoreBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocument(\Innova\CollecticielBundle\Entity\Document $document)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocument', [$document]);

        return parent::setDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocument', []);

        return parent::getDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setDropzone(\Innova\CollecticielBundle\Entity\Dropzone $dropzone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDropzone', [$dropzone]);

        return parent::setDropzone($dropzone);
    }

    /**
     * {@inheritDoc}
     */
    public function getDropzone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDropzone', []);

        return parent::getDropzone();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecordOrTransmit($recordOrTransmit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecordOrTransmit', [$recordOrTransmit]);

        return parent::setRecordOrTransmit($recordOrTransmit);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecordOrTransmit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecordOrTransmit', []);

        return parent::getRecordOrTransmit();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppreciation($appreciation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppreciation', [$appreciation]);

        return parent::setAppreciation($appreciation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppreciation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppreciation', []);

        return parent::getAppreciation();
    }

    /**
     * {@inheritDoc}
     */
    public function addChoiceCriteria(\Innova\CollecticielBundle\Entity\ChoiceCriteria $choiceCriteria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChoiceCriteria', [$choiceCriteria]);

        return parent::addChoiceCriteria($choiceCriteria);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChoiceCriteria(\Innova\CollecticielBundle\Entity\ChoiceCriteria $choiceCriteria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChoiceCriteria', [$choiceCriteria]);

        return parent::removeChoiceCriteria($choiceCriteria);
    }

    /**
     * {@inheritDoc}
     */
    public function getChoiceCriterias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChoiceCriterias', []);

        return parent::getChoiceCriterias();
    }

}
