<?php

namespace Proxies\__CG__\Claroline\CoreBundle\Entity\Widget;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Widget extends \Claroline\CoreBundle\Entity\Widget\Widget implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'plugin', 'name', 'isConfigurable', 'isExportable', 'isDisplayableInWorkspace', 'isDisplayableInDesktop', 'defaultWidth', 'defaultHeight', 'roles'];
        }

        return ['__isInitialized__', 'id', 'plugin', 'name', 'isConfigurable', 'isExportable', 'isDisplayableInWorkspace', 'isDisplayableInDesktop', 'defaultWidth', 'defaultHeight', 'roles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Widget $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlugin($plugin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlugin', [$plugin]);

        return parent::setPlugin($plugin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlugin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlugin', []);

        return parent::getPlugin();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function isConfigurable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isConfigurable', []);

        return parent::isConfigurable();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfigurable($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfigurable', [$bool]);

        return parent::setConfigurable($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setExportable($isExportable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportable', [$isExportable]);

        return parent::setExportable($isExportable);
    }

    /**
     * {@inheritDoc}
     */
    public function isExportable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExportable', []);

        return parent::isExportable();
    }

    /**
     * {@inheritDoc}
     */
    public function isDisplayableInWorkspace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDisplayableInWorkspace', []);

        return parent::isDisplayableInWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayableInWorkspace($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayableInWorkspace', [$bool]);

        return parent::setDisplayableInWorkspace($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDisplayableInWorkspace($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDisplayableInWorkspace', [$bool]);

        return parent::setIsDisplayableInWorkspace($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function isDisplayableInDesktop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDisplayableInDesktop', []);

        return parent::isDisplayableInDesktop();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayableInDesktop($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayableInDesktop', [$bool]);

        return parent::setDisplayableInDesktop($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDisplayableInDesktop($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDisplayableInDesktop', [$bool]);

        return parent::setIsDisplayableInDesktop($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultWidth', []);

        return parent::getDefaultWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultWidth($defaultWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultWidth', [$defaultWidth]);

        return parent::setDefaultWidth($defaultWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultHeight', []);

        return parent::getDefaultHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultHeight($defaultHeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultHeight', [$defaultHeight]);

        return parent::setDefaultHeight($defaultHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole(\Claroline\CoreBundle\Entity\Role $role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$role]);

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole(\Claroline\CoreBundle\Entity\Role $role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', [$role]);

        return parent::removeRole($role);
    }

}
