<?php

namespace Proxies\__CG__\UJM\ExoBundle\Entity\Attempt;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Answer extends \UJM\ExoBundle\Entity\Attempt\Answer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'id', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'ip', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'score', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'feedback', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'tries', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'data', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'usedHints', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'paper', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'questionId', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'uuid'];
        }

        return ['__isInitialized__', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'id', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'ip', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'score', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'feedback', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'tries', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'data', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'usedHints', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'paper', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'questionId', '' . "\0" . 'UJM\\ExoBundle\\Entity\\Attempt\\Answer' . "\0" . 'uuid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Answer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp($ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', [$ip]);

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', []);

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore($score)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore', [$score]);

        return parent::setScore($score);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore', []);

        return parent::getScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeedback($feedback)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeedback', [$feedback]);

        return parent::setFeedback($feedback);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeedback()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedback', []);

        return parent::getFeedback();
    }

    /**
     * {@inheritDoc}
     */
    public function setTries($tries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTries', [$tries]);

        return parent::setTries($tries);
    }

    /**
     * {@inheritDoc}
     */
    public function getTries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTries', []);

        return parent::getTries();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsedHints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsedHints', []);

        return parent::getUsedHints();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsedHint($hintId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsedHint', [$hintId]);

        return parent::addUsedHint($hintId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsedHint($hintId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsedHint', [$hintId]);

        return parent::removeUsedHint($hintId);
    }

    /**
     * {@inheritDoc}
     */
    public function setPaper(\UJM\ExoBundle\Entity\Attempt\Paper $paper)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaper', [$paper]);

        return parent::setPaper($paper);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaper()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaper', []);

        return parent::getPaper();
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestionId', []);

        return parent::getQuestionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestionId($questionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestionId', [$questionId]);

        return parent::setQuestionId($questionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUuid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUuid', []);

        return parent::getUuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUuid($uuid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUuid', [$uuid]);

        return parent::setUuid($uuid);
    }

}
