<?php

namespace Proxies\__CG__\Innova\PathBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Step extends \Innova\PathBundle\Entity\Step implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'activity', 'parameters', 'activityHeight', 'lvl', 'order', 'parent', 'children', 'path', 'condition', 'inheritedResources'];
        }

        return ['__isInitialized__', 'id', 'activity', 'parameters', 'activityHeight', 'lvl', 'order', 'parent', 'children', 'path', 'condition', 'inheritedResources'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Step $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivity', []);

        return parent::getActivity();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivity(\Claroline\CoreBundle\Entity\Resource\Activity $activity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivity', [$activity]);

        return parent::setActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function getParameters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParameters', []);

        return parent::getParameters();
    }

    /**
     * {@inheritDoc}
     */
    public function setParameters(\Claroline\CoreBundle\Entity\Activity\ActivityParameters $parameters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParameters', [$parameters]);

        return parent::setParameters($parameters);
    }

    /**
     * {@inheritDoc}
     */
    public function setLvl($lvl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLvl', [$lvl]);

        return parent::setLvl($lvl);
    }

    /**
     * {@inheritDoc}
     */
    public function getLvl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLvl', []);

        return parent::getLvl();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder($order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath(\Innova\PathBundle\Entity\Path\Path $path = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', [$path]);

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', []);

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Innova\PathBundle\Entity\Step $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', []);

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function hasChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasChildren', []);

        return parent::hasChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function addChild(\Innova\PathBundle\Entity\Step $step)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChild', [$step]);

        return parent::addChild($step);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChild(\Innova\PathBundle\Entity\Step $step)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChild', [$step]);

        return parent::removeChild($step);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkspace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkspace', []);

        return parent::getWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessibleFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessibleFrom', []);

        return parent::getAccessibleFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessibleUntil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessibleUntil', []);

        return parent::getAccessibleUntil();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityHeight', []);

        return parent::getActivityHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivityHeight($activityHeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivityHeight', [$activityHeight]);

        return parent::setActivityHeight($activityHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getInheritedResources()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInheritedResources', []);

        return parent::getInheritedResources();
    }

    /**
     * {@inheritDoc}
     */
    public function addInheritedResource(\Innova\PathBundle\Entity\InheritedResource $inheritedResource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInheritedResource', [$inheritedResource]);

        return parent::addInheritedResource($inheritedResource);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInheritedResource(\Innova\PathBundle\Entity\InheritedResource $inheritedResource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInheritedResource', [$inheritedResource]);

        return parent::removeInheritedResource($inheritedResource);
    }

    /**
     * {@inheritDoc}
     */
    public function hasInheritedResource($resourceId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasInheritedResource', [$resourceId]);

        return parent::hasInheritedResource($resourceId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropagatedResources($lvl = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropagatedResources', [$lvl]);

        return parent::getPropagatedResources($lvl);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentsSecondaryResources()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentsSecondaryResources', []);

        return parent::getParentsSecondaryResources();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondition(\Innova\PathBundle\Entity\StepCondition $condition = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondition', [$condition]);

        return parent::setCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondition', []);

        return parent::getCondition();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
