<?php

namespace Proxies\__CG__\Claroline\FlashCardBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Note extends \Claroline\FlashCardBundle\Entity\Note implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'id', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'noteType', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'deck', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'fieldValues', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'cards'];
        }

        return ['__isInitialized__', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'id', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'noteType', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'deck', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'fieldValues', '' . "\0" . 'Claroline\\FlashCardBundle\\Entity\\Note' . "\0" . 'cards'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Note $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoteType(\Claroline\FlashCardBundle\Entity\NoteType $obj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoteType', [$obj]);

        return parent::setNoteType($obj);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoteType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoteType', []);

        return parent::getNoteType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeck(\Claroline\FlashCardBundle\Entity\Deck $obj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeck', [$obj]);

        return parent::setDeck($obj);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeck()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeck', []);

        return parent::getDeck();
    }

    /**
     * {@inheritDoc}
     */
    public function addFieldValue(\Claroline\FlashCardBundle\Entity\FieldValue $obj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFieldValue', [$obj]);

        return parent::addFieldValue($obj);
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldValue($fieldId, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldValue', [$fieldId, $value]);

        return parent::setFieldValue($fieldId, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function setFieldValues(\Doctrine\Common\Collections\ArrayCollection $obj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFieldValues', [$obj]);

        return parent::setFieldValues($obj);
    }

    /**
     * {@inheritDoc}
     */
    public function getFieldValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFieldValues', []);

        return parent::getFieldValues();
    }

    /**
     * {@inheritDoc}
     */
    public function addCard(\Claroline\FlashCardBundle\Entity\Card $obj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCard', [$obj]);

        return parent::addCard($obj);
    }

    /**
     * {@inheritDoc}
     */
    public function setCards(\Doctrine\Common\Collections\ArrayCollection $obj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCards', [$obj]);

        return parent::setCards($obj);
    }

    /**
     * {@inheritDoc}
     */
    public function getCards()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCards', []);

        return parent::getCards();
    }

}
