<?php

namespace Proxies\__CG__\HeVinci\CompetencyBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ability extends \HeVinci\CompetencyBundle\Entity\Ability implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'id', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'name', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'minActivityCount', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'competencyAbilities', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'activities', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'activityCount', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'level'];
        }

        return ['__isInitialized__', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'id', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'name', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'minActivityCount', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'competencyAbilities', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'activities', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'activityCount', '' . "\0" . 'HeVinci\\CompetencyBundle\\Entity\\Ability' . "\0" . 'level'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ability $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinActivityCount($count)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinActivityCount', [$count]);

        return parent::setMinActivityCount($count);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinActivityCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinActivityCount', []);

        return parent::getMinActivityCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompetencyAbilities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompetencyAbilities', []);

        return parent::getCompetencyAbilities();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevel(\HeVinci\CompetencyBundle\Entity\Level $level)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevel', [$level]);

        return parent::setLevel($level);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function isLinkedToActivity(\Claroline\CoreBundle\Entity\Resource\Activity $activity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLinkedToActivity', [$activity]);

        return parent::isLinkedToActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function linkActivity(\Claroline\CoreBundle\Entity\Resource\Activity $activity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'linkActivity', [$activity]);

        return parent::linkActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivity(\Claroline\CoreBundle\Entity\Resource\Activity $activity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivity', [$activity]);

        return parent::removeActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivities', []);

        return parent::getActivities();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
